name: JobWatcher
version: "0.1.8"
slug: jobwatcher
description: Serve jobs.db through a FastAPI and scrape on demand
arch:
  - amd64
  - aarch64
startup: services
boot: auto
options: {}
schema: {}
ports:
  8001/tcp: 8001
