name: JobWatcher
version: "0.1.4"
slug: jobwatcher
description: Serve jobs.db through a FastAPI and scrape on demand
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
panel_icon: mdi:briefcase
options:
  pages_daily: 1
  pages_backfill: 5
  year_filter: 2025
  source_url: "https://helijobs.net/category/pilot/?tag=oceania"
  page_pattern: "https://helijobs.net/category/pilot/page/{page}/?tag=oceania"
schema:
  pages_daily: int
  pages_backfill: int
  year_filter: int
  source_url: str
  page_pattern: str
ports:
  "8001/tcp": 8001
map:
  - config:rw   # so we can keep jobs.db under /config/jobwatcher
