name: JobWatcher
version: "0.1.52"
slug: jobwatcher
description: Serve jobs.db through a FastAPI and scrape on demand
arch:
  - amd64
  - aarch64
map:
  - type: data
    read_only: False
startup: services
boot: auto
ports:
  8001/tcp: 8001
options: {}
schema: {}
