name: "JobWatcher API"
version: "1.0.16"
slug: "jobwatcher"
description: "Custom FastAPI add-on for job listings"
arch:
  - amd64
  - aarch64
startup: services
boot: auto
options: {}
schema: {}
ports:
  8001/tcp: 8001
